// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0
// source: order_loyalty.proto

package pb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConclusionUserBalanceUseCase_Conclude_FullMethodName = "/v1.ConclusionUserBalanceUseCase/Conclude"
)

// ConclusionUserBalanceUseCaseClient is the client API for ConclusionUserBalanceUseCase service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConclusionUserBalanceUseCaseClient interface {
	Conclude(ctx context.Context, in *ConclusionRequest, opts ...grpc.CallOption) (*ConclusionResponse, error)
}

type conclusionUserBalanceUseCaseClient struct {
	cc grpc.ClientConnInterface
}

func NewConclusionUserBalanceUseCaseClient(cc grpc.ClientConnInterface) ConclusionUserBalanceUseCaseClient {
	return &conclusionUserBalanceUseCaseClient{cc}
}

func (c *conclusionUserBalanceUseCaseClient) Conclude(ctx context.Context, in *ConclusionRequest, opts ...grpc.CallOption) (*ConclusionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConclusionResponse)
	err := c.cc.Invoke(ctx, ConclusionUserBalanceUseCase_Conclude_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConclusionUserBalanceUseCaseServer is the server API for ConclusionUserBalanceUseCase service.
// All implementations must embed UnimplementedConclusionUserBalanceUseCaseServer
// for forward compatibility.
type ConclusionUserBalanceUseCaseServer interface {
	Conclude(context.Context, *ConclusionRequest) (*ConclusionResponse, error)
	mustEmbedUnimplementedConclusionUserBalanceUseCaseServer()
}

// UnimplementedConclusionUserBalanceUseCaseServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConclusionUserBalanceUseCaseServer struct{}

func (UnimplementedConclusionUserBalanceUseCaseServer) Conclude(context.Context, *ConclusionRequest) (*ConclusionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Conclude not implemented")
}
func (UnimplementedConclusionUserBalanceUseCaseServer) mustEmbedUnimplementedConclusionUserBalanceUseCaseServer() {
}
func (UnimplementedConclusionUserBalanceUseCaseServer) testEmbeddedByValue() {}

// UnsafeConclusionUserBalanceUseCaseServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConclusionUserBalanceUseCaseServer will
// result in compilation errors.
type UnsafeConclusionUserBalanceUseCaseServer interface {
	mustEmbedUnimplementedConclusionUserBalanceUseCaseServer()
}

func RegisterConclusionUserBalanceUseCaseServer(s grpc.ServiceRegistrar, srv ConclusionUserBalanceUseCaseServer) {
	// If the following call pancis, it indicates UnimplementedConclusionUserBalanceUseCaseServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConclusionUserBalanceUseCase_ServiceDesc, srv)
}

func _ConclusionUserBalanceUseCase_Conclude_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConclusionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConclusionUserBalanceUseCaseServer).Conclude(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConclusionUserBalanceUseCase_Conclude_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConclusionUserBalanceUseCaseServer).Conclude(ctx, req.(*ConclusionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConclusionUserBalanceUseCase_ServiceDesc is the grpc.ServiceDesc for ConclusionUserBalanceUseCase service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConclusionUserBalanceUseCase_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.ConclusionUserBalanceUseCase",
	HandlerType: (*ConclusionUserBalanceUseCaseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Conclude",
			Handler:    _ConclusionUserBalanceUseCase_Conclude_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order_loyalty.proto",
}
